---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: recommendation-service
spec:
  source:
    type: Git
    sourceSecret:
      name: retail-git-ssh-key
    git:
      uri: 'git@github.com:tejones/retailstoreofthefuture.git'
      ref: develop-pl
    contextDir: recommendation-service/
  strategy:
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: 'recommendation-service:latest'
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: recommendation-service
spec:
  lookupPolicy:
    local: false
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: prediction-service
spec:
  source:
    type: Git
    sourceSecret:
      name: retail-git-ssh-key
    git:
      uri: 'git@github.com:tejones/retailstoreofthefuture.git'
      ref: develop-pl
    contextDir: prediction-service/
  strategy:
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: 'prediction-service:latest'
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: prediction-service
spec:
  lookupPolicy:
    local: false
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: visualization-service
spec:
  source:
    type: Git
    sourceSecret:
      name: retail-git-ssh-key
    git:
      uri: 'git@github.com:tejones/retailstoreofthefuture.git'
      ref: develop-pl
    contextDir: visualization-app/
  strategy:
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: 'visualization-service:latest'
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: visualization-service
spec:
  lookupPolicy:
    local: false
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: customer-simulation-service
spec:
  source:
    type: Git
    sourceSecret:
      name: retail-git-ssh-key
    git:
      uri: 'git@github.com:tejones/retailstoreofthefuture.git'
      ref: develop-pl
    contextDir: scenario-player/
  strategy:
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: 'customer-simulation-service:latest'
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: customer-simulation-service
spec:
  lookupPolicy:
    local: false

---

